<div class="row">
	<div class="col-20">
		<img src="img/contenido/Rafael_D_Mercado.png" alt="Face closeup of Rafael Mercado">
	</div>
	<div class="col-60">
		<h2>
			Rafael D. Mercado Solis
		</h2>
		<p>
			Professor of Material Engineering at the Faculty of Mechanical and Electrical Engineering, Universidad Autonoma de Nuevo Leon.
			<br>
			His scientific expertise includes quenching modeling, tempering kinetics, residual stresses and surface engineering.
		</p>
		<h2 class="blue-text">
			<a href="mailto:rafa.mercado@mx-uk-htn.net">rafa.mercado@mx-uk-htn.net</a>
		</h2>
	</div>
</div>
<div class="row">
	<div class="col-20">
		<img src="img/contenido/Bradley_P_Wayne.jpg" alt="Face closeup of Bradley Wayne">
	</div>
	<div class="col-60">
		<h2>
			Bradley P. Wynne
		</h2>
		<p>
			Professor of Metallurgy at the Department of Material's Science and Engineering, University of Sheffield. <br>
			His scientific expertise includes advanced mechanical testing, phase transformation, diffusion, electron microscopy and modelling.
		</p>
		<h2 class="blue-text">
			<a href="mailto:luis.leduc@mx-uk-htn.net">luis.leduc@mx-uk-htn.net</a>
		</h2>
	</div>
</div>