<style>
.ng-hide, [ng-cloak] {
	display: none !important;
}

.ng-show {
	display: block !important;
}
body {
	background-color: #343334;
}
.cabeza {
	height: 200px;
	background-color: #fff;
}
.cabeza2 {
	height: 64px;
	background-color: #343334;
	max-width: 960px;
	margin: 0 auto;
	position: relative;
}
.fondo {
	padding-top: 200px;
	background-color: #343334;
}
.contenido {
	max-width: 960px;
	margin: 0 auto;
	min-height: 420px;
	position: relative;
}

.tabbable input {
	width: 95%;
	background-color: #e6e6e6;
	color: #000;
	border-radius: 0;
}

.tabbable select {
	width: 98%;
	background-color: #e6e6e6;
	color: #000;
	border-radius: 0;
}

.mitad {
	width: 45.5% !important;
}

select.mitad {
	width: 48.5% !important;
}
form {
	margin: 0;
}
.subtitulo {
	color: #fff;
	padding-bottom: 25px;
	border-bottom: 2px solid #873588;
	margin-bottom: 25px;
	width: 300px;
}
.caja {
	border-bottom: 5px solid #873588;
	margin-bottom: 25px;
	width: 300px;
	height: 210px;
	position: absolute;
	top: -300px;
	left: 50px;
	background-color: #c2c2c2;
	opacity: 0.9;
}

nav ul {
	list-style: none;
}

nav li {
	float: left;
	background-color: #343334;
}
.innerMenu10 {
	width: 680px;
}
</style>
<div class="cabeza2">
<div class='dataTypeMenu menu left horizontal innerMenu10 ' data-type='Menu' data-name='Top Menu' id='innerMenu10'><nav>			<ul>
		<li id='mainMenuElement0innerMenu10' class='innerMenu10_category image_wa'> <A href="http://solisbarrera.com/index.html" title="INICIO" class="category">INICIO</A></li>
		<li id='mainMenuElement1innerMenu10' class='innerMenu10_category image_wa'> <A href="http://solisbarrera.com/about.html" title="SERVICIOS" class="category">SERVICIOS</A></li>
		<li id='mainMenuElement2innerMenu10' class='innerMenu10_category image_wa'> <A href="http://solisbarrera.com/gallery.html" title="CASOS DE ÉXITO" class="category">CASOS DE ÉXITO</A></li>

		<li id='mainMenuElement2innerMenu10' class='innerMenu10_categoryDown image_wa'> <A href="http://solisbarrera.com/hgn/" title="SUBE TU CURRÍCULUM" class="category">CURRÍCULUM</A></li>

		<li id='mainMenuElement3innerMenu10' class='innerMenu10_category image_wa'> <A href="http://solisbarrera.com/BIBLIOTECA.html" title="BIBLIOTECA" class="category">BIBLIOTECA</A></li>
		<li id='mainMenuElement4innerMenu10' class='innerMenu10_category image_wa'> <A href="http://solisbarrera.com/Page1.html" title="CONTACTO" class="category">CONTACTO</A></li>
	</ul>
</nav></div>
</div>
<div class="cabeza">

</div>
<div class="fondo">
	<div class="contenido">
	<div class="caja">
				<p style="text-align: center;margin-top: 25px;">INGRESA TUS DATOS Y SE PARTE DE NUESTRA BOLSA DE TRABAJO</p>
				<p style="text-align: center; position: absolute; bottom: -40px; color: #fff; width: 300px;">COMPETITIVIDAD EN CAPITAL HUMANO</p>
	</div>
	<form>
		<div ng-tabs class="tabbable">
			<ul class="nav nav-pills nav-stacked" style="width: 100px;  float:left; margin-left: 50px; ">
				<div class="subtitulo">
				INFORMACIÓN
				</div>
				<li ng-tab-head="active">
					<a href="#" ng-click="$event.preventDefault()">Personal</a>
				</li>
				<li ng-tab-head>
					<a href="#" ng-click="$event.preventDefault()">Estudios</a>
				</li>
				<li ng-tab-head>
					<a href="#" ng-click="$event.preventDefault()">Trayectoria</a>
				</li>
			</ul>
				<div class="tab-content" style="width: 500px; float:right; margin-top: 45px;">
					<div ng-tab-body="" class="tab-pane">
						<input type="text" placeholder="Nombre" ng-model="forma.nombre" required>
						<input type="text" placeholder="Apellido" ng-model="forma.apellidos" required>
						<input class="mitad" type="text" placeholder="Edad" ng-model="forma.edad" required>
						<select class="mitad" ng-model="forma.sexo" required>
							<option value="">Sexo</option>
							<option value="Masculino">Masculino</option>
							<option value="Femenino">Femenino</option>
						</select>
						<input type="text" placeholder="Estado de residencia" ng-model="forma.residencia" required>
						<select class="mitad" ng-model="forma.area1" required>
							<option value="">Estado</option>
							<option value="1">Aguascalientes</option>
							<option value="2">Baja California</option>
							<option value="3">Baja California Sur</option>
							<option value="4">Campeche</option>
							<option value="5">Chiapas</option>
							<option value="6">Chihuahua</option>
							<option value="7">Coahuila</option>
							<option value="8">Colima</option>
							<option value="9">Distrito Federal</option>
							<option value="10">Durango</option>
							<option value="11">Estado de México</option>
							<option value="12">Guanajuato</option>
							<option value="13">Guerrero</option>
							<option value="14">Hidalgo</option>
							<option value="15">Jalisco</option>
							<option value="16">Michoacán</option>
							<option value="17">Morelos</option>
							<option value="18">Nayarit</option>
							<option value="19">Nuevo León</option>
							<option value="20">Oaxaca</option>
							<option value="21">Puebla</option>
							<option value="22">Querétaro</option>
							<option value="23">Quintana Roo</option>
							<option value="24">San Luis Potosí</option>
							<option value="25">Sinaloa</option>
							<option value="26">Sonora</option>
							<option value="27">Tabasco</option>
							<option value="28">Tamaulipas</option>
							<option value="29">Tlaxcala</option>
							<option value="30">Veracruz</option>
							<option value="31">Yucatán</option>
							<option value="32">Zacatecas</option>
						</select>
						<input class="mitad" type="text" placeholder="Teléfono" ng-model="forma.telefono" required>
						<input class="mitad" type="text" placeholder="Email" ng-model="forma.email" required>

					</div>
					<div ng-tab-body="" class="tab-pane">
						<input type="text" placeholder="Carrera" ng-model="forma.carrera" required>
						<input type="text" placeholder="Institución" ng-model="forma.inst_carrera" required>
						<input type="text" placeholder="Maestría" ng-model="forma.maestria">
						<input type="text" placeholder="Institución" ng-model="forma.inst_maestria">
						<select class="mitad" ng-model="forma.ingles" required>
							<option value="">Inglés</option>
							<option value="1">Nulo (No tiene conocimientos del idioma.)</option>
							<option value="2">Principiante (Entiende textos y algunas expresiones al escuchar. No lo habla.)</option>
							<option value="3">Intermedio (Puede leerlo y escribirlo. Solo habla y entiende expresiones básicas.)</option>
							<option value="4">Avanzado (Puede leerlo y escribirlo. Capaz de establecer conversaciones.)</option>
							<option value="5">Nativo (Domina completamente el idioma.)</option>
						</select>
						<input class="mitad" type="text" placeholder="Otros idiomas" ng-model="forma.otros_idiomas">
					</div>
					<div ng-tab-body="" class="tab-pane">
						<input type="text" placeholder="Último puesto" ng-model="forma.ultimo_puesto">
						<input type="text" placeholder="Empresa" ng-model="forma.empresa">
						<br>
						<select class="mitad" ng-model="forma.area1" required>
							<option value="">Área de experiencia</option>
							<option value="1">Administración</option>
							<option value="2">Arquitectura</option>
							<option value="3">Construcción</option>
							<option value="4">Contabilidad</option>
							<option value="5">Compras</option>
							<option value="6">Crédito y Cobranza</option>
							<option value="7">Derecho</option>
							<option value="8">Dirección General</option>
							<option value="9">Diseño Industrial</option>
							<option value="10">Diseño Gráfico</option>
							<option value="11">Diseño Web</option>
							<option value="12">Distribución</option>
							<option value="13">Educación</option>
							<option value="14">Gastronomía</option>
							<option value="15">Gerencia General</option>
							<option value="16">Ingeniería</option>
							<option value="17">Investigación y Desarrollo</option>
							<option value="18">Logística</option>
							<option value="19">Mantenimiento</option>
							<option value="20">Medicina</option>
							<option value="21">Mercadotecnia</option>
							<option value="22">Operación</option>
							<option value="23">Producción</option>
							<option value="24">Publicidad</option>
							<option value="25">Recepción y Apoyo Administrativo</option>
							<option value="26">Recursos Humanos</option>
							<option value="27">Relaciones Públicas</option>
							<option value="28">Salud y Belleza</option>
							<option value="29">Servicio al Cliente</option>
							<option value="30">Sistemas Computacionales (Hardware)</option>
							<option value="31">Tecnologías de Información (Software)</option>
							<option value="32">Transportación</option>
							<option value="33">Turismo</option>
							<option value="34">Ventas</option>
						</select>
						<select class="mitad" ng-model="forma.tiempo1" required>
							<option value="">Tiempo</option>
							<option value="1">Menos de 1 año</option>
							<option value="2">De 1 a 3 años</option>
							<option value="3">De 3 a 5 años</option>
							<option value="4">De 5 a 10 años</option>
							<option value="5">Más de 10 años</option>
						</select>
						<br>
						<select class="mitad" ng-model="forma.area2">
							<option value="">Área de experiencia</option>
							<option value="1">Administración</option>
							<option value="2">Arquitectura</option>
							<option value="3">Construcción</option>
							<option value="4">Contabilidad</option>
							<option value="5">Compras</option>
							<option value="6">Crédito y Cobranza</option>
							<option value="7">Derecho</option>
							<option value="8">Dirección General</option>
							<option value="9">Diseño Industrial</option>
							<option value="10">Diseño Gráfico</option>
							<option value="11">Diseño Web</option>
							<option value="12">Distribución</option>
							<option value="13">Educación</option>
							<option value="14">Gastronomía</option>
							<option value="15">Gerencia General</option>
							<option value="16">Ingeniería</option>
							<option value="17">Investigación y Desarrollo</option>
							<option value="18">Logística</option>
							<option value="19">Mantenimiento</option>
							<option value="20">Medicina</option>
							<option value="21">Mercadotecnia</option>
							<option value="22">Operación</option>
							<option value="23">Producción</option>
							<option value="24">Publicidad</option>
							<option value="25">Recepción y Apoyo Administrativo</option>
							<option value="26">Recursos Humanos</option>
							<option value="27">Relaciones Públicas</option>
							<option value="28">Salud y Belleza</option>
							<option value="29">Servicio al Cliente</option>
							<option value="30">Sistemas Computacionales (Hardware)</option>
							<option value="31">Tecnologías de Información (Software)</option>
							<option value="32">Transportación</option>
							<option value="33">Turismo</option>
							<option value="34">Ventas</option>
						</select>
						<select class="mitad" ng-model="forma.tiempo2">
							<option value="">Tiempo</option>
							<option value="1">Menos de 1 año</option>
							<option value="2">De 1 a 3 años</option>
							<option value="3">De 3 a 5 años</option>
							<option value="4">De 5 a 10 años</option>
							<option value="5">Más de 10 años</option>
						</select>
						<br>
						<select class="mitad" ng-model="forma.area3">
							<option value="">Área de experiencia</option>
							<option value="1">Administración</option>
							<option value="2">Arquitectura</option>
							<option value="3">Construcción</option>
							<option value="4">Contabilidad</option>
							<option value="5">Compras</option>
							<option value="6">Crédito y Cobranza</option>
							<option value="7">Derecho</option>
							<option value="8">Dirección General</option>
							<option value="9">Diseño Industrial</option>
							<option value="10">Diseño Gráfico</option>
							<option value="11">Diseño Web</option>
							<option value="12">Distribución</option>
							<option value="13">Educación</option>
							<option value="14">Gastronomía</option>
							<option value="15">Gerencia General</option>
							<option value="16">Ingeniería</option>
							<option value="17">Investigación y Desarrollo</option>
							<option value="18">Logística</option>
							<option value="19">Mantenimiento</option>
							<option value="20">Medicina</option>
							<option value="21">Mercadotecnia</option>
							<option value="22">Operación</option>
							<option value="23">Producción</option>
							<option value="24">Publicidad</option>
							<option value="25">Recepción y Apoyo Administrativo</option>
							<option value="26">Recursos Humanos</option>
							<option value="27">Relaciones Públicas</option>
							<option value="28">Salud y Belleza</option>
							<option value="29">Servicio al Cliente</option>
							<option value="30">Sistemas Computacionales (Hardware)</option>
							<option value="31">Tecnologías de Información (Software)</option>
							<option value="32">Transportación</option>
							<option value="33">Turismo</option>
							<option value="34">Ventas</option>
						</select>
						<select class="mitad" ng-model="forma.tiempo3">
							<option value="">Tiempo</option>
							<option value="1">Menos de 1 año</option>
							<option value="2">De 1 a 3 años</option>
							<option value="3">De 3 a 5 años</option>
							<option value="4">De 5 a 10 años</option>
							<option value="5">Más de 10 años</option>
						</select>
						<br>
						<select ng-model="forma.rango_sueldo" required>
							<option value="">Rango de sueldo</option>
							<option value="1">$5,000.00 - $10,000.00</option>
							<option value="2">$10,000.00 - $15,000.00</option>
							<option value="3">$15,000.00 - $20,000.00</option>
							<option value="4">$20,000.00 - $30,000.00</option>
							<option value="5">$30,000.00 - $40,000.00</option>
							<option value="6">$40,000.00 - $50,000.00</option>
							<option value="7">$50,000.00 - $70,000.00</option>
							<option value="8">$70,000.00 - $90,000.00</option>
							<option value="9">$90,00.00 - $120,000.00</option>
							<option value="10">$120,000.00 - $150,000.00</option>
						</select>
					</div>
				</div>
				<div style="clear: both; float: right;">
				<p style="color: #fff; background-color: {{color}};color: {{font}};text-align: center; width: 510px;" ng-show="message">
					{{message}}
				</p>
				<br>
				</div>
				<div style="clear: both; float: right;">
				<button style="clear: both; width: 300px; float: right;" class="md-primary md-raised" ngf-select ng-model="forma.file" accept="application/*">Seleccionar Curriculum</button>
				<p style="color: #fff;" ng-show="forma.file">{{forma.file.name}}
				<br>{{forma.file.size/1024 | number:1}} KB</p>
				<button style="clear: both; float: right; margin-top: 15px;" ng-click="upload()">Enviar</button>
				</div>
			</div>
		</form>
	</div>
</div>