<section id="pagecontent" layout="row" flex ng-controller="AdminController">
<style type="text/css">
	.tajetaConfig {
		min-width: 960px;
	}
</style>
<md-card class="tajetaConfig">
	<img ng-src="{{imagePath}}" class="md-card-image">
	<md-card-content>
	<h2 class="md-title">Personas</h2>
		{{loading}}
		<md-content class="md-padding">
		<md-input-container>
			<label>Buscar Personas </label>
			<input ng-model="searchName" />
		</md-input-container>
		<md-input-container>
			<label>Buscar áreas </label>
			<md-select ng-model="search.area1">
				<md-option ng-repeat="area in areas track by $index" value="{{$index}}">
					{{area}}
				</md-option>
			</md-select>
		</md-input-container>
		<md-input-container>
			<label>Buscar salario </label>
			<md-select ng-model="search.rango_sueldo">
				<md-option ng-repeat="sueldo in sueldo track by $index" value="{{$index}}">
					{{sueldo}}
				</md-option>
			</md-select>
		</md-input-container>
		<md-input-container>
			<label>Buscar inglés </label>
			<md-select ng-model="search.ingles">
				<md-option ng-repeat="ingles in ingles track by $index" value="{{$index}}">
					{{ingles}}
				</md-option>
			</md-select>
		</md-input-container>
		<md-input-container>
			<label>Buscar Residencia </label>
			<md-select ng-model="search.residencia">
				<md-option ng-repeat="estado in estado track by $index" value="{{$index}}">
					{{estado}}
				</md-option>
			</md-select>
		</md-input-container>
		<md-input-container>
			<label>Buscar sexo </label>
			<md-select ng-model="search.sexo">
				<md-option value="0"></md-option>
				<md-option value="Masculino">Masculino</md-option>
				<md-option value="Femenino">Femenino</md-option>
			</md-select>
		</md-input-container>
			<md-list>
				<md-list-item class="md-3-line" ng-repeat="persona in personas | filter:search:true | filter:searchName">
					<div class="md-list-item-text" layout="column">
						<h3>{{ persona.nombre }} {{ persona.apellidos }}</h3>
						<h4>{{ persona.empresa }}</h4>
					</div>
					<md-button class="md-secondary" ng-click="personaDialog($event, $index)">Ver</md-button>
					<md-divider ></md-divider>
				</md-list-item>
			</md-list>
		</md-content>
	</md-card-content>
</md-card>
</div>
</section>