<!DOCTYPE html>
<html ng-app="haganeApp">
<head>
	<base href="<?= $this->config['document_root']; ?>">
	<meta charset="utf-8">
	<title>UANL</title>

	<!-- STYLES -->
	<link rel="stylesheet" type="text/css" href="css/reset.css" />
	<link rel="stylesheet" type="text/css" href="css/slick.css" />
	<link rel="stylesheet" type="text/css" href="css/slick-theme.css" />
	<link rel="stylesheet" href="css/webicons.css" media="screen" title="no title" charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css" />

	<!-- FONTS -->
	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>

	<!-- JAVASCRIPTS -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type="text/javascript" src="js/slick.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
	<script type="text/javascript" src="js/angular-slick.min.js"></script>
	<script type="text/javascript" src="js/angular/haganeApp.js"></script>
	<script type="text/javascript" src="js/angular/controllers.js"></script>
</head>
<body>
	<div class="page-wrap">
		<div class="header">
			<div class="content">
				<div class="imagen-logo">
					<a href="#"><img src="img/menu/logo.png"></a>
					<div class="greeting">
						<?php if ($this->auth->isAuth()) : ?>
						<span class="welcome">welcome</span>
						<span class="user"><?= $this->user->getUsername(); ?></span>
						<a href="logout" style="font-size: 8px">(Logout)</a>
						<?php else: ?>
						<a href="login">Login</a>
					<?php endif; ?>
					
					</div>
					<div class="patrocinadores">
						<a href="http://www.uanl.mx/"><img src="img/menu/uni.jpg"></a>
						<a href="http://www.conacyt.mx/"><img src="img/menu/conacyt.jpg"></a>
						<a href="http://newtonfoundation.publishpath.com/"><img src="img/menu/newtfund.jpg"></a>
						<a href="https://www.britishcouncil.org.mx/"><img src="img/menu/brtcouncil.jpg"></a>
						<a href="http://www.sheffield.ac.uk/"><img src="img/menu/tuos.jpg"></a>
					</div>
					
				</div>
				<!--
				<div class="follow-us">
					 CAMBIO 1 EN EL DISEñO AL DIA 10 DE DIC
					<span class="subtitle">Follow US</span>
					<div class="social svg">
						<a href="#" class="webicon googleplus">Google+</a>
						<a href="#" class="webicon twitter">Twitter</a>
						<a href="#" class="webicon youtube">YouTube</a>
						<a href="#" class="webicon facebook">Facebook</a>
						<a href="#" class="webicon linkedin">LinkedIn</a>
					</div>
					-->
					
					
					<!--</div> -->
			</div>
		</div>
		<div class="nav">
			<div class="content">
				<a href="./" class="subtitulonav">HEAT TREATMENT NETWORK</a>
				<ul>
					<li><a href="User/sign_up">Signup</a></li>
					<li><a href="Downloads">Downloads</a></li>
					<li><a href="Events">Events</a></li>
					<li><a href="Index/contacto">Contact</a></li>
				</ul>
				<input id="searchbar" type="search" placeholder="Search">
			</div>
		</div>
		<div class="main-view">
			<?= $this->view; ?>
		</div>
		<div class="footers">
			<div class="footer up">
				<div class="content">
					<div class="caja">
						<span class="subtitulo">Useful Resources</span>
						<div class="caja-content">
							<ul>
								<li>link no.1</li>
								<li>link no.1</li>
								<li>link no.1</li>
								<li>link no.1</li>
							</ul>
						</div>
					</div>
					<div class="caja">
						<span class="subtitulo">Contact</span>
						<div class="caja-content">
							<table>
								<tr>
									<td class="label">address</td><td>lorem ipsum st. MX</td>
								</tr>
								<tr>
									<td class="label">email</td><td>lorem ipsu@uk-mx-htc.com</td>
								</tr>
								<tr>
									<td class="label">phone</td><td>52-1234 972030</td>
								</tr>
								<tr>
									<td class="label">map</td><td>link.to.map</td>
								</tr>
							</table>
						</div>
					</div>
					<div class="caja">
						<span class="subtitulo">Recent Articles</span>
						<div class="caja-content">
							<ul class="articles">
								<li><img src="#" alt="Art.IMG" /><p>Lorem ipsum dolor sit amet, consectetur</p></li>
								<li><img src="#" alt="Art.IMG" /><p>Lorem ipsum dolor sit amet, consectetur</p></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="footer down">
				<div class="content">
					<ul>
						<li><a href="User/sign_up">Signup</a></li>
						<li><a href="Downloads">Downloads</a></li>
						<li><a href="Events">Events</a></li>
						<li><a href="Index/contacto">Contact</a></li>
					</ul>
					<div class="copyright">
						<span class="copy">HTN Copyright 2015</span>
						<span class="design">designed by BLACKMAMBA </span>
					</div>
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript">
	$('.fade').slick({
	  dots: true,
	  infinite: true,
	  speed: 500,
	  fade: true,
	  cssEase: 'linear'
	});
	
</script>
</body>
</html>
