<!DOCTYPE html>
<html ng-app="haganeApp">
<head>
	<meta charset="UTF-8">
	<base href="<?= $this->config['document_root']; ?>">

	<!-- Stylesheets -->
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc1/angular-material.min.css">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Roboto'>
	<link rel="stylesheet" type="text/css" href="css/style.css">

	<title>SBC Admin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Javascripts -->
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js"></script>
	<script src="js/haganeApp.js"></script>
	<script src="js/Config.js"></script>
	<script src="js/Controllers.js"></script>
</head>
<body ng-controller="MainController">
<section layout="row" flex>
	<md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')">
		<md-toolbar class="md-primary">
			<h1 class="md-toolbar-tools">SBC</h1>
		</md-toolbar>
		<md-content layout-padding ng-controller="LeftCtrl">
		<md-list>
				<?php if($this->auth->isAuth()) :?>
						<md-list-item ng-class="{active : isActive('/Admin/index')}" ng-href="Admin/index">Inicio</md-list-item>
						<md-divider></md-divider>
						<md-list-item ng-class="{active : isActive('logout')}" ng-href="logout">Cerrar Sesion</md-list-item>
				<?php else : ?>
						<md-list-item ng-class="{active : isActive('login')}" ng-href="login" class="md-primary">Login</md-list-item>
				<?php endif; ?>
			</md-list>
		</md-content>
	</md-sidenav>

	<section layout="column" flex>
		<md-toolbar>
			<div class="md-toolbar-tools">
				<md-button ng-click="toggleLeft()" hide-gt-lg class="md-icon-button">
					<md-icon md-font-set="material-icons">menu</md-icon>
				</md-button>
				<h2>{{toolbar_title}}</h2>
				</md-button>
			</div>
		</md-toolbar>
	<md-content flex style="padding: 15px;">
		<div class="loader">
			<md-progress-circular md-mode="{{loading}}"></md-progress-circular>
		</div>
		<?= $this->view; ?>
	</md-content>
	</section>
</section>
</body>
</html>