<!DOCTYPE html>
<html ng-app="haganeApp">
<head>
	<meta charset="UTF-8">
	<base href="<?= $this->config['document_root']; ?>">

	<!-- Stylesheets -->
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc1/angular-material.min.css">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Roboto'>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" type="text/css" href="css/boot.css">


	<title>SBC Curriculum</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="global.webydo.com/v8/base.css"/>
	<link rel="stylesheet" type="text/css" href="IP_Master_PT_RTL.masterc82c.css?v=9034519415"/>
	<link rel="stylesheet" type="text/css" href="BIBLIOTECAc82c.css?v=9034519415"/>
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald&amp;subset=latin,cyrillic-ext,greek-ext,greek,latin-ext,cyrillic"/>
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald:300,400,700|Angkor:400|Open%20Sans:300,300italic,400,italic,600,600italic,700,700italic,800,800italic|Ubuntu%20Condensed:400|Muli:300,300italic,400,italic&amp;subset=latin,cyrillic-ext,greek-ext,greek,latin-ext,cyrillic"/>
	<link rel="icon" href="images7.webydo.com/91/9128512/3958/EB8D8096-0775-CF8D-7D59-3844052D4523.png" type="image/x-icon"/>
	<link rel="shortcut icon" href="images7.webydo.com/91/9128512/3958/EB8D8096-0775-CF8D-7D59-3844052D4523.png" type="image/x-icon"/>



	<!-- Javascripts -->
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
	  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js"></script>
	<script src="js/tabs.js"></script>
	<script src="js/ng-file-upload-all.min.js"></script>
	<script src="js/haganeApp.js"></script>
	<script src="js/Config.js"></script>
	<script src="js/Controllers.js"></script>
</head>
<body ng-controller="MainController">
<?= $this->view; ?>
</body>
</html>